import { ConverterPlugin } from "../engine/types";

export const currencyPlugin: ConverterPlugin = {
  id: "currency",
  name: "Currency",
  description: "Convert USD, EUR, GBP, JPY, CAD, AUD, BDT, INR, and major global currencies.",
  iconName: "DollarSign",
  baseUnitId: "usd",
  units: [
    {
      id: "usd",
      name: "US Dollar",
      symbol: "$",
      category: "currency",
      aliases: ["usd", "us dollar", "dollar", "dollars", "$"],
      ratioToBase: 1,
    },
    {
      id: "eur",
      name: "Euro",
      symbol: "€",
      category: "currency",
      aliases: ["eur", "euro", "euros", "€"],
      ratioToBase: 1.08,
    },
    {
      id: "gbp",
      name: "British Pound",
      symbol: "£",
      category: "currency",
      aliases: ["gbp", "pound", "pounds", "sterling", "£"],
      ratioToBase: 1.27,
    },
    {
      id: "jpy",
      name: "Japanese Yen",
      symbol: "¥",
      category: "currency",
      aliases: ["jpy", "yen", "¥"],
      ratioToBase: 0.0066,
    },
    {
      id: "cad",
      name: "Canadian Dollar",
      symbol: "CA$",
      category: "currency",
      aliases: ["cad", "canadian dollar", "cad$"],
      ratioToBase: 0.73,
    },
    {
      id: "aud",
      name: "Australian Dollar",
      symbol: "A$",
      category: "currency",
      aliases: ["aud", "australian dollar", "aud$"],
      ratioToBase: 0.65,
    },
    {
      id: "bdt",
      name: "Bangladeshi Taka",
      symbol: "৳",
      category: "currency",
      aliases: ["bdt", "taka", "bangladeshi taka", "৳"],
      ratioToBase: 0.0084,
    },
    {
      id: "inr",
      name: "Indian Rupee",
      symbol: "₹",
      category: "currency",
      aliases: ["inr", "rupee", "rupees", "indian rupee", "₹"],
      ratioToBase: 0.012,
    },
    {
      id: "chf",
      name: "Swiss Franc",
      symbol: "CHF",
      category: "currency",
      aliases: ["chf", "swiss franc", "franc"],
      ratioToBase: 1.13,
    },
    {
      id: "cny",
      name: "Chinese Yuan",
      symbol: "¥",
      category: "currency",
      aliases: ["cny", "yuan", "rmb"],
      ratioToBase: 0.14,
    },
  ],
};
