import { ConverterPlugin } from "../engine/types";

export const digitalPlugin: ConverterPlugin = {
  id: "digital",
  name: "Digital Storage",
  description: "Convert Bytes, KB, MB, GB, TB, PB, KiB, MiB, GiB, TiB.",
  iconName: "HardDrive",
  baseUnitId: "byte",
  units: [
    {
      id: "byte",
      name: "Byte",
      symbol: "B",
      category: "digital",
      aliases: ["byte", "bytes", "b"],
      ratioToBase: 1,
    },
    {
      id: "kilobyte",
      name: "Kilobyte (Decimal)",
      symbol: "KB",
      category: "digital",
      aliases: ["kilobyte", "kilobytes", "kb"],
      ratioToBase: 1000,
    },
    {
      id: "megabyte",
      name: "Megabyte (Decimal)",
      symbol: "MB",
      category: "digital",
      aliases: ["megabyte", "megabytes", "mb"],
      ratioToBase: 1000000,
    },
    {
      id: "gigabyte",
      name: "Gigabyte (Decimal)",
      symbol: "GB",
      category: "digital",
      aliases: ["gigabyte", "gigabytes", "gb"],
      ratioToBase: 1000000000,
    },
    {
      id: "terabyte",
      name: "Terabyte (Decimal)",
      symbol: "TB",
      category: "digital",
      aliases: ["terabyte", "terabytes", "tb"],
      ratioToBase: 1000000000000,
    },
    {
      id: "kibibyte",
      name: "Kibibyte (Binary)",
      symbol: "KiB",
      category: "digital",
      aliases: ["kibibyte", "kibibytes", "kib"],
      ratioToBase: 1024,
    },
    {
      id: "mebibyte",
      name: "Mebibyte (Binary)",
      symbol: "MiB",
      category: "digital",
      aliases: ["mebibyte", "mebibytes", "mib"],
      ratioToBase: 1048576,
    },
    {
      id: "gibibyte",
      name: "Gibibyte (Binary)",
      symbol: "GiB",
      category: "digital",
      aliases: ["gibibyte", "gibibytes", "gib"],
      ratioToBase: 1073741824,
    },
    {
      id: "tebibyte",
      name: "Tebibyte (Binary)",
      symbol: "TiB",
      category: "digital",
      aliases: ["tebibyte", "tebibytes", "tib"],
      ratioToBase: 1099511627776,
    },
  ],
};
