import { ConverterPlugin } from "../engine/types";

export const lengthPlugin: ConverterPlugin = {
  id: "length",
  name: "Length",
  description: "Convert meters, feet, inches, kilometers, miles, yards, and nautical miles.",
  iconName: "Ruler",
  baseUnitId: "meter",
  units: [
    {
      id: "meter",
      name: "Meter",
      symbol: "m",
      category: "length",
      aliases: ["meter", "meters", "metre", "metres", "m"],
      ratioToBase: 1,
    },
    {
      id: "kilometer",
      name: "Kilometer",
      symbol: "km",
      category: "length",
      aliases: ["kilometer", "kilometers", "kilometre", "kilometres", "km"],
      ratioToBase: 1000,
    },
    {
      id: "centimeter",
      name: "Centimeter",
      symbol: "cm",
      category: "length",
      aliases: ["centimeter", "centimeters", "centimetre", "centimetres", "cm"],
      ratioToBase: 0.01,
    },
    {
      id: "millimeter",
      name: "Millimeter",
      symbol: "mm",
      category: "length",
      aliases: ["millimeter", "millimeters", "millimetre", "millimetres", "mm"],
      ratioToBase: 0.001,
    },
    {
      id: "foot",
      name: "Foot",
      symbol: "ft",
      category: "length",
      aliases: ["foot", "feet", "ft", "'"],
      ratioToBase: 0.3048,
    },
    {
      id: "inch",
      name: "Inch",
      symbol: "in",
      category: "length",
      aliases: ["inch", "inches", "in", '"'],
      ratioToBase: 0.0254,
    },
    {
      id: "yard",
      name: "Yard",
      symbol: "yd",
      category: "length",
      aliases: ["yard", "yards", "yd"],
      ratioToBase: 0.9144,
    },
    {
      id: "mile",
      name: "Mile",
      symbol: "mi",
      category: "length",
      aliases: ["mile", "miles", "mi"],
      ratioToBase: 1609.344,
    },
    {
      id: "nautical_mile",
      name: "Nautical Mile",
      symbol: "nmi",
      category: "length",
      aliases: ["nautical mile", "nautical miles", "nmi", "NM"],
      ratioToBase: 1852,
    },
  ],
};
